### ISSUE TITLE
Use extension installer

### ISSUE THREAD

**Issue by shadowhand** [eloquent/phpstan-phony#10]
https://github.com/phpstan/extension-installer allows for automatic detection of installed phpstan extensions.

**Comment by shadowhand** [comment]
Never mind, I see that it has already been done in #9, I just hadn't updated to `0.5.0`.

**Comment by ezzatron** [comment]
Would be nice if phpstan released a `1.x` version. Then I could do the same here to avoid things like this. But based on https://github.com/phpstan/phpstan/issues/1010 that doesn't look like it's going to happen soon.
