### ISSUE TITLE
Not compatible with PHPStan v0.11

### ISSUE THREAD

**Issue by enumag** [eloquent/phpstan-phony#8]
https://github.com/phpstan/phpstan/releases/tag/0.11

**Comment by ezzatron** [comment]
Thanks for the heads up.

**Comment by ezzatron** [comment]
Fixed in [0.4.0](https://github.com/eloquent/phpstan-phony/releases/0.4.0).

**Comment by enumag** [comment]
Wow that was fast! Thanks!

**Comment by ezzatron** [comment]
No problem, it was pretty easy this time because there were no applicable BC breaks in PHPStan.
